
class AirportSchedule_Config:
    cargoIATAList = [
        "FX",
        "5X",
        "8K",
        "9K",
        "HT"
    ]

    cargoNameList = [
        "Cargo",
        "DHL",
        "Southern Air",
        "Bismillah Airlines",
        "Kalitta Air",
        "MASkargo",
        "Air Hong Kong",
        "Freight",
        "UPS",
        "FedEx",
        "SF",
        "Atlas",
        "AHK",
        "Suparna",
        "Postal",
        "Shell Aircraft",
        "Ceiba",
        "CSA Air",
        "USA Jet",
        "K-Mile Air",
        "Silk Way West Airlines",
        "Cardig Air",
        "Morningstar Air Express",
        "SkyLink Express",
        "Loong Air",
        "Private owner",
        "Quest Diagnostics",
        "NetJets",
        "AirShare",
        "Flexjet",
        "Ameriflight",
        "Martinaire",
        "Boutique Air",
        "Wiggins Airways",
        "Air Transport International",
        "Southern Air",
        "Nolinor Aviation",
        "Air Transport International",
        "Empire Airlines",
        "Antonov Airlines",
        "Alaska Central Express",
        "Everts Air Alaska",
        "ATRAN - Aviatrans Cargo Airlines",
        "Western Global Airlines",
        "Antonov Airlines (Antonov Design Bureau)",
        "National Airlines",
        "ABX Air",
        "Amerijet International",
        "Jet Logistics"
    ]

    cargoAircraftList = [
        "33F",
        "77F",
        "B741",
        "B77F",
        "74Y",
        "74N"
    ]
