from api.api import *

def initialize_routes(api):
    api.add_resource(RpiStatusApi, '/api/v1/status')
    api.add_resource(TestApi, '/api/v1/test')
    api.add_resource(LocationApi, '/api/v1/location')
    api.add_resource(SpeedTestApi, '/api/v1/speedTest')
    api.add_resource(FlightScheduleApi, '/api/v1/flightSchedule/<id>/<status_code>')
    api.add_resource(AirportApi, '/api/v1/airport/<id>')
    api.add_resource(CurrentFlightApi, '/api/v1/currentFlight/<id>/<status_code>')
    api.add_resource(AirportWeatherApi, '/api/v1/weather/<id>')
    api.add_resource(FlightDatesCountApi, '/api/v1/flightDateCount')
    api.add_resource(CarsInfoApi, '/api/v1/carsInfo/<model>/<zipcode>')
    api.add_resource(FlightNumByAirlineApi, '/api/v1/flight_num/<airline>')
    api.add_resource(AllAirportsApi, '/api/v1/all_airports')
    api.add_resource(AirportDetailApi, '/api/v1/airport_detail/<id>')
    api.add_resource(AllianceApi, '/api/v1/alliance/<id>')
    api.add_resource(AirportFlightPathApi, '/api/v1/airport_flightPath/<id>')
    api.add_resource(AirportTimeSeriesApi, '/api/v1/timeSeries/<id>')
    api.add_resource(AirportPopDestinationApi, '/api/v1/airport/pop_destination/<id>')
    api.add_resource(AirlinePopDestinationApi, '/api/v1/airline/pop_destination/<id>')